import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/sets'
import HomePage from '@/components/templates/home'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: {toggleTheme: Function}) {
  const [windowWidth, setWindowWidth] = useState(0)

  useEffect(() => {
    setWindowWidth(window.innerWidth)
    window.onresize = () => setWindowWidth(window.innerWidth)
  }, [])

  return (
    <>
      <Head>
        <title> Pechinchou - As Melhores Promoções da Internet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Header toggleTheme={props.toggleTheme} windowWidth={windowWidth}/>
      
      <HomePage toggleTheme={props.toggleTheme} windowWidth={windowWidth}/>
    </>
  )
}
