import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/sets'
import HomePage from '@/components/templates/home'
import { useEffect, useState } from 'react'
import { connectUser } from '@/apiConnection'
import Footer from '@/components/sets/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: {toggleTheme: Function}) {
  const [windowWidth, setWindowWidth] = useState(-1)
  const [user, setUser] = useState({
    id: 0,
    username: "",
  })        

  useEffect(() => {
    setWindowWidth(window.innerWidth)
    window.onresize = () => setWindowWidth(window.innerWidth);

    (async function () { setUser(await connectUser()) })()
  }, [])

  return (
    <>
      <Head>
        <title> Pechinchou - As Melhores Promoções da Internet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Header toggleTheme={props.toggleTheme} windowWidth={windowWidth} user={user} type='home'/>
      
      <HomePage toggleTheme={props.toggleTheme} windowWidth={windowWidth}/>
    </>
  )
}
